// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYZVxBvFrdfjCIfs6PCaPy75vZ5TmwdI',
    appId: '1:93566381279:web:99182f4c1d3dc205ce0d6a',
    messagingSenderId: '93566381279',
    projectId: 'trivialpoursuittristanmartin',
    authDomain: 'trivialpoursuittristanmartin.firebaseapp.com',
    storageBucket: 'trivialpoursuittristanmartin.appspot.com',
    measurementId: 'G-R5C2K7W9JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQSVKFJO_lDEBW-JZC-j6qcFv86jQZ0g',
    appId: '1:93566381279:android:8bf9c649985f10a2ce0d6a',
    messagingSenderId: '93566381279',
    projectId: 'trivialpoursuittristanmartin',
    storageBucket: 'trivialpoursuittristanmartin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnNP_bHPlSp75gLaD1m60a92pMWEbju8',
    appId: '1:93566381279:ios:be64e15dad115168ce0d6a',
    messagingSenderId: '93566381279',
    projectId: 'trivialpoursuittristanmartin',
    storageBucket: 'trivialpoursuittristanmartin.appspot.com',
    iosClientId:
        '93566381279-1tjef2imgili2thh3rk0bcnq31e9eteu.apps.googleusercontent.com',
    iosBundleId: 'fges.cyber.trivialPursuitTristanSixMartinGobert',
  );
}
